name: CI/CD for Frontend

# Khi nào workflow sẽ chạy
on:
  push:
    branches:
      - main

# Các bước thực thi
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Hệ điều hành để chạy workflow

    steps:
      # Bước 1: Checkout code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Chọn phiên bản Node.js phù hợp với Next.js

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Build ứng dụng Next.js
      - name: Build Next.js app
        run: npm run build

      # Bước 5: Login vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Biến bí mật chứa username
          password: ${{ secrets.DOCKER_PASSWORD }} # Biến bí mật chứa password

      # Bước 6: Build và push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t hoang24/workflows-fe:latest .
          docker push hoang24/workflows-fe:latest

      # Bước 7: Deploy ứng dụng lên VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            docker pull hoang24/workflows-fe:latest
            echo "Pulled frontend image successfully"
